CREATE TABLE IF NOT EXISTS public.vendas_hotmart
(
    id_correspondente bigint NOT NULL,
    purchase_original_offer_price_currency_value character varying(250) COLLATE pg_catalog."default",
    purchase_original_offer_price_value double precision,
    purchase_checkout_country_iso character varying(250) COLLATE pg_catalog."default",
    purchase_checkout_country_name character varying(250) COLLATE pg_catalog."default",
    purchase_order_bump_is_order_bump boolean,
    purchase_approved_date timestamp without time zone,
    purchase_order_date timestamp without time zone,
    purchase_price_currency_value character varying(250) COLLATE pg_catalog."default",
    purchase_price_value double precision,
    purchase_buyer_ip character varying(1000) COLLATE pg_catalog."default",
    purchase_payment_installments_number integer,
    purchase_payment_type character varying(250) COLLATE pg_catalog."default",
    purchase_full_price_currency_value character varying(250) COLLATE pg_catalog."default",
    purchase_full_price_value double precision,
    purchase_invoice_by character varying(250) COLLATE pg_catalog."default",
    purchase_transaction character varying(250) COLLATE pg_catalog."default",
    purchase_status character varying(250) COLLATE pg_catalog."default",
    buyer_address_zipcode character varying(250) COLLATE pg_catalog."default",
    buyer_address_country character varying(250) COLLATE pg_catalog."default",
    buyer_address_address character varying(1000) COLLATE pg_catalog."default",
    buyer_address_city character varying(1000) COLLATE pg_catalog."default",
    buyer_document character varying(250) COLLATE pg_catalog."default",
    buyer_name character varying(500) COLLATE pg_catalog."default",
    buyer_checkout_phone character varying(250) COLLATE pg_catalog."default",
    buyer_email character varying(350) COLLATE pg_catalog."default",
    id character varying(250) COLLATE pg_catalog."default",
    creation_date timestamp without time zone,
    event character varying(250) COLLATE pg_catalog."default",
    version character varying(250) COLLATE pg_catalog."default",
    purchase_tracking_source_sck character varying(250) COLLATE pg_catalog."default",
    purchase_tracking_source character varying(1750) COLLATE pg_catalog."default",
    utm_source character varying(250) COLLATE pg_catalog."default",
    utm_medium character varying(250) COLLATE pg_catalog."default",
    utm_campaign character varying(250) COLLATE pg_catalog."default",
    utm_campaign_id character varying(250) COLLATE pg_catalog."default",
    utm_term character varying(250) COLLATE pg_catalog."default",
    utm_content character varying(250) COLLATE pg_catalog."default",
    marketplace_commission_value double precision,
    marketplace_commission_currency_value character varying(250) COLLATE pg_catalog."default",
    producer_commission_value double precision,
    producer_commission_currency_value character varying(250) COLLATE pg_catalog."default",
    affiliates_commission_value double precision,
    affiliates_commission_currency_value character varying(250) COLLATE pg_catalog."default",
    addon_commission_value double precision,
    addon_commission_currency_value character varying(250) COLLATE pg_catalog."default",
    CONSTRAINT unique_transaction_vendas_hotmart UNIQUE (purchase_transaction),
    CONSTRAINT id_fk_vendas_hotmart FOREIGN KEY (id_correspondente)
        REFERENCES public.ofertas_hotmart (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
)

TABLESPACE pg_default;
